-- Batch insert for Adjectives (وەسف(هەڤالناڤ))
-- Categorized based on character count:
-- classic: 2-5 letters
-- hard_words: 6+ letters
-- word_fever: exactly 5 letters
-- secret_word: 2+ letters
-- battle: exactly 5 letters

INSERT INTO public.words (word, hint, category, mode_tags) VALUES
('باش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('خراب', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('مەزن', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('بچووک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('درێژ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('کورت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('گەرم', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('سار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('گەنج', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('جوان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('نەجوان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('زانا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('نەزان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('دەولەمەند', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('هەژار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('گران', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ئەرزان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('سڤک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('زوو', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('درەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێدەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێھێز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێکار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێمنەت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێهۆش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێباک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێبێھن', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('تژی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('بەتاڵ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('شرین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('تال', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ترش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('سوێر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('جیاواز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('وەکهەڤ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('نەرم', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ڕەق', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پاک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پیس', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']),
('زیرەک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێوار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('دلخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('خەمگین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێزار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('ترسنۆک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('نەترس', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێبار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێباهی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێگومان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێژان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێڕەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبایەخ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبەرامبەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێدەستوور', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێزارکەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێمفا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),

  ('دژوار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ساناھی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('دلخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خەمگین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('پیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('گەنج', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بھێز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('لاواز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('تیژ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('کول', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('دوور', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('نێزیک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ستویر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('تەنک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('زڤر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('حلی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ڤەبووی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گرتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ئاشکرا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڤەشارتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('شل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('تیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ڕاستگۆ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('درەوین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('وێرەک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ترسنۆک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ماندی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('مرتاح', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شەرمین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێشەرم', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('خاڤ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('تۆخ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ئارام', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەسەکنی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ژیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('دین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('سادە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ئالۆز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('گرنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بمفا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بێمفا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('تەمام', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەتەمام', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تایبەت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گشتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('پێگەھشتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('کۆرە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('کەڕ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ھشیار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نڤستی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕاستەقینە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەختە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلۆڤان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('دلسۆز', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلڕەق', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بێزار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پەشێمان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خوار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('دروست', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خەلەت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کێم', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('پڕ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('زێدە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('تێر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('سەیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ئاسایی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێھنخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێھنگەن', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەربەست', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گرێدایی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('فێنک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('تژی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ڕەنگاوڕەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('زیرەک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('توند', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ژێھاتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گێژ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بەربەلاڤ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('دیار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('سەرکەفتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('نخافتی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕویس', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('ئازاد', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زیندانی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('پەسەند', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێگونەھ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تاوانبار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('مەرد', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بەخیل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('قەھوەیی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('پیڤازی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('مۆر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('سافی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('خواروڤیچ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خەمسار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەشبین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕەشبین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بەختەوەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێبەخت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('چاڤبرسی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('قایل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('مەغروور', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خوەپەرست', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕووخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئەنیگرێ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەنگخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تەزی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('کەل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('برژاندی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('کەلیای', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەنی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('تامخوەش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێتام', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەقەت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('شەل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('گوھگران', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('لال', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('گڕۆڤڕ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('چارگۆشە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('سێگۆشە', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تێکەل', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئالاندی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('قەلشی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شکەستی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تەندروست', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('کەڤنار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەڤچەرخ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('دانعەمر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕاوەستیای', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('لڤۆک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بێلڤین', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێھنفرەھ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێھنتەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('فەرمی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەفەرمی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('باوەڕپێکری', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('تەخیر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پێشوەخت', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەرزان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بھاگران', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێبھا', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نایاب', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کێموکاسی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێکێموکاسی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بەرچاڤ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('نەدیار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('زەلال', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شێلی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('کویڤی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کەدیکری', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕند', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('سەرکێش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('گوھدار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('بێسەروبەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕێکوپێک', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بریقەدار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھشکەساڵی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاڤدار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خەیاڵی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('واقیعی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئەفسانەیی', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەرسوورھێنەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('باڵکێش', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێزارکەر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەستیار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('سڕ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('گەرموگوڕ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('شەنگ', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('جوان', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['classic', 'secret_word']::text[]),
  ('نازدار', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[]),
  ('خۆڕاگر', 'وەسف(ھەڤالناڤ)', 'وەسف(ھەڤالناڤ)', ARRAY['hard_words', 'secret_word']::text[])
ON CONFLICT (word, hint) DO NOTHING;
