-- Batch insert for Adjectives (وەسف(هەڤالناڤ))
-- Categorized based on character count:
-- classic: 2-5 letters
-- hard_words: 6+ letters
-- word_fever: exactly 5 letters
-- secret_word: 2+ letters
-- battle: exactly 5 letters

INSERT INTO public.words (word, hint, category, mode_tags) VALUES
('باش', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('خراب', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('مەزن', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('بچووک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('درێژ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('کورت', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('گەرم', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('سار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('گەنج', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پیر', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('جوان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('نەجوان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('زانا', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('نەزان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('دەولەمەند', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('هەژار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('گران', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ئەرزان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('سڤک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('زوو', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('درەنگ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێدەنگ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێھێز', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێکار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێمنەت', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێهۆش', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێباک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێبێھن', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبەر', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('تژی', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('بەتاڵ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('شرین', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('تال', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ترش', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('سوێر', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('جیاواز', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('وەکهەڤ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('نەرم', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('ڕەق', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پاک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('پیس', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'secret_word']),
('زیرەک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێوار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('دلخوەش', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('خەمگین', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێزار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('ترسنۆک', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('نەترس', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێبار', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێباهی', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێگومان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێژان', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle']),
('بێڕەنگ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبایەخ', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێبەرامبەر', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێدەستوور', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێزارکەر', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['hard_words', 'secret_word']),
('بێمفا', 'وەسف(هەڤالناڤ)', 'وەسف(هەڤالناڤ)', ARRAY['classic', 'word_fever', 'secret_word', 'battle'])
ON CONFLICT (word, hint) DO NOTHING;
