-- فایلێ تایبەت ب ناڤێ مرۆڤان (Human Names)
-- بتنێ ڤی فایلی Copy بکە و ل Supabase SQL Editor دابنێ و Run بکە

INSERT INTO public.words (word, hint, category, mode_tags)
VALUES
  ('نارین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھێڤی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('مێرخاس', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئالان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕۆژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئەڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شێرکۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئارام', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڤیان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('کاروان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەڤاڵ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پەیمان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕێباز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سامان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕۆناھی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەژار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئازاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەورۆز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('لاڤا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('زانا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڕۆژدا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پێشەوا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('چنار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ھەلگورد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دلڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھێمن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سۆزدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کانی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڕێبین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('جوان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سیپان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئارین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلمان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خەبات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕێناس', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('تارا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('کۆڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('مزگین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دیار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('بێریڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھۆگر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دلێر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ساکار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئاواز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بارزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕووبار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سیروان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ناز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ئاری', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('نیاز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شەڤگەڕ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەردار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('پەری', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ھەژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کارزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕۆژان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئاسۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('بەناز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('فەرھاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('میدیا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کاوە', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شەپۆل', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زۆزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھەکار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەوزاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕۆژھات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دلۆڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نالیا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کاردۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بەیان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئاراس', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئامەد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئاریا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئالا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ئەڤراز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئارڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئەرسەلان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('برۆسک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سۆز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('باران', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بەشدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بەرھەم', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بەختیار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بەڕێز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('چیا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دلشاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دەرباز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەروون', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دارا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دێرین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلگەش', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('داستان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەریا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('فەرھەنگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەیلان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەشبین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('گولان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھێژا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ھەڵمەت', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەندرین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەردی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھۆشمەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھێلین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھێرش', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('جوامێر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کامیران', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کەیوان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کیڤی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('لۆران', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لاوک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('مەریوان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('مەتین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('میران', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('مازن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('مەم', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شێروان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نشتیمان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نازک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('پەیام', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پشتیوان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('پەروین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕێبەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕێدیر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕێنجبەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕاستی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەرکەفت', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەفین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('تێکۆشەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڤینۆس', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('وەزیر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھشیار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('یادگار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('زەردەشت', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('زاگرۆس', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('زین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شادمان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('شەنگێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شیلان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پەیڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کۆچەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕەڤەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕۆژگار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('شاھۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('شرین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('بلند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڕێڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بێوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلشێر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دژوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خێرۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سەربەست', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نێچیرڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('جەنگاوەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('زیرەک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('عەگید', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زنار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('پێشەنگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بۆتان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بادین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بەھدین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('باپیر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕەشۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('جەمبەلی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سیابەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕزگار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕۆژڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕۆژدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('چەکدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('چەلەنگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەروێش', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('فەرزەندە', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('گۆڤەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھەوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ھۆزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ژێھات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لاوین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لەزگین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('مێھڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نێچیر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕێزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شەرڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('وەلات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خەلات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زێرەڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('زێدان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زێبار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلسۆز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نالی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('نەبەز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕامان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('هەڤال', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کاردۆخ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('باوەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دیاکۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕێکان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لێزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕەوەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەنگەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ژێگر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڕەنج', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ھەرێم', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('باگەڕ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شەمزین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئارتین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاکام', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەھەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ھێزدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نیھاد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڕاستگۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('تۆفان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('وریا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('زانیار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاشتی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئاڤدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاڤشین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بێری', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('بەرفین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('بهار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('جانێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('چاڤشین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('جیھان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دەلال', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دیلان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دلبەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دیمەن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('گولێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('گولستان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کەوێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('کنێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('لۆرین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نالین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نازدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕەنگین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕووکەن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سێڤێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سینەم', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شۆخان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خەزال', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('خەجێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('زەریا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زینێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ئاڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('باخان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بنار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('چرا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دیرۆک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئەلند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('فێنک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('فرمێسک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕۆندک', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('گەشین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('هاڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('هاوژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('لالەش', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لانە', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('لاڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('لیلاڤ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نێرگز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نیگار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نەرمین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نیان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('نووژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نووپێل', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('راپەڕین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('روومەت', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سازان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەنار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەیران', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سیبەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شەڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڤەژین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زێڕین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ئالین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('مینا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڤیندا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('نازێ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[])
,
  ('چیاڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دانا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دلمان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دیدەڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەشتی', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زێوەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سێڤدین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('شاهین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڤەهێل', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڤەگێڕ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('قەندیل', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کوردۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('میرزا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('هۆشەنگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('هیوا', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('هونەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ژڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڕێنجبەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەرمەد', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('باهۆز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بەندەوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('پەروەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دادڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('رۆستەم', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('رێڤینگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('رێوان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('زێوە', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سامان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('ڤەژەن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('کرێکار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('مەلەڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نالبەند', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('یەکبوون', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('پارێز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('پەیڤان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('دەڤەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('دارین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سەروەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('کەسەر', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بژار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('دابین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ڤینوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('گەلهات', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نەدیار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('نیوار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('وار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('مەردان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاهەنگ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ڕەوشەن', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سۆلین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('شەهناز', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('ئاهین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('سۆزان', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('بارین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('ژینۆ', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('سپێدە', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[]),
  ('هێڤیدار', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['hard_words', 'secret_word']::text[]),
  ('سەما', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'secret_word']::text[]),
  ('پڕڤین', 'ناڤێ مرۆڤان', 'ناڤێ مرۆڤان', ARRAY['classic', 'word_fever', 'secret_word', 'battle']::text[])
ON CONFLICT (word, hint) DO NOTHING;
