-- ==========================================
-- PEYVÇÎN 2.0: FINAL STANDARDIZED SETUP
-- ==========================================

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  nickname TEXT,
  avatar_url TEXT,
  city TEXT DEFAULT NULL, -- Starts empty as requested
  is_kurdistan BOOLEAN DEFAULT TRUE,
  country_code TEXT DEFAULT 'KD',
  level INTEGER DEFAULT 1,
  xp INTEGER DEFAULT 0,
  daily_streak INTEGER DEFAULT 0,
  
  -- Currencies
  fils INTEGER DEFAULT 100,  -- Adjusted: 1000 -> 100
  derhem INTEGER DEFAULT 50,
  dinar INTEGER DEFAULT 0,
  
  -- Inventory
  magnets INTEGER DEFAULT 2,
  hints INTEGER DEFAULT 5,    -- Adjusted: 10 -> 5
  skips INTEGER DEFAULT 0,
  
  -- Collections
  owned_avatars JSONB DEFAULT '["default"]'::JSONB,
  equipped_avatar TEXT DEFAULT 'default',
  unlocked_themes JSONB DEFAULT '["default"]'::JSONB,
  equipped_theme TEXT DEFAULT 'default'
);

-- 2. MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  content TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_nickname TEXT
);

-- 3. ENABLE ROW LEVEL SECURITY
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Messages are viewable by everyone" ON public.messages;
CREATE POLICY "Messages are viewable by everyone" ON public.messages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Auth users can insert messages" ON public.messages;
CREATE POLICY "Auth users can insert messages" ON public.messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 5. AUTOMATIC PROFILE CREATOR
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname, country_code)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'nickname', 'یاریکەر'),
    COALESCE(new.raw_user_meta_data->>'country_code', 'KD')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. SOCIAL TABLES (FRIENDSHIPS & PRIVATE MESSAGES)
CREATE TABLE IF NOT EXISTS public.friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  friend_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' -- 'pending', 'accepted'
);

CREATE TABLE IF NOT EXISTS public.private_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  recipient_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE
);

ALTER TABLE public.friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.private_messages ENABLE ROW LEVEL SECURITY;

-- 8. SOCIAL POLICIES
-- Private Messages: Users can see messages they sent or received, send new ones, and update (mark as read) ones they received.
DROP POLICY IF EXISTS "Users can view own private messages" ON public.private_messages;
CREATE POLICY "Users can view own private messages" ON public.private_messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

DROP POLICY IF EXISTS "Users can send private messages" ON public.private_messages;
CREATE POLICY "Users can send private messages" ON public.private_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "Users can update received messages" ON public.private_messages;
CREATE POLICY "Users can update received messages" ON public.private_messages FOR UPDATE USING (auth.uid() = recipient_id);

-- Friendships: Users can see and manage their own friendships.
DROP POLICY IF EXISTS "Users can view own friendships" ON public.friendships;
CREATE POLICY "Users can view own friendships" ON public.friendships FOR SELECT USING (auth.uid() = user_id OR auth.uid() = friend_id);

DROP POLICY IF EXISTS "Users can manage own friendships" ON public.friendships;
CREATE POLICY "Users can manage own friendships" ON public.friendships FOR ALL USING (auth.uid() = user_id OR auth.uid() = friend_id);

-- 9. ENABLE REALTIME FOR SOCIAL
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'friendships') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.friendships;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'private_messages') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.private_messages;
  END IF;
END $$;
