const fs = require('fs');
const path = require('path');

// Mocking the environment to read wordList.js
const wordListPath = 'd:/Peyivcin App/src/data/wordList.js';
const content = fs.readFileSync(wordListPath, 'utf8');

// Simple extraction using regex since we can't easily import ES modules here
function extractArray(name) {
    const startRegex = new RegExp(`const ${name} = \\[`, 'g');
    const startMatch = startRegex.exec(content);
    if (!startMatch) return [];
    
    let balance = 1;
    let endIdx = startMatch.index + startMatch[0].length;
    let currentContent = content.substring(startMatch.index + startMatch[0].length);
    
    // This is a bit naive but works for standard arrays
    let finalArrayContent = "";
    let i = 0;
    while (balance > 0 && i < currentContent.length) {
        if (currentContent[i] === '[') balance++;
        else if (currentContent[i] === ']') balance--;
        if (balance > 0) finalArrayContent += currentContent[i];
        i++;
    }
    
    // Clean up comments and format as JSON-like
    const cleaned = finalArrayContent
        .replace(/\/\/.*$/gm, '') // remove line comments
        .replace(/\s+/g, ' ')     // collapse whitespace
        .trim();
        
    // Use a trick: wrap in brackets and eval safely-ish or parse
    // Since it's trusted local code, we can extract objects
    const objects = [];
    const objRegex = /\{\s*word:\s*"([^"]+)",\s*hint:\s*"([^"]+)"(?:,\s*category:\s*"([^"]+)")?\s*\}/g;
    let m;
    while ((m = objRegex.exec(cleaned)) !== null) {
        objects.push({
            word: m[1],
            hint: m[2],
            category: m[3] || 'general'
        });
    }
    return objects;
}

const classic = extractArray('classicWords');
const mamak = extractArray('mamakWords');
const hard = extractArray('hardWords');
const fever = extractArray('wordFeverWords');

const masterMap = new Map();

function addToMap(list, tag) {
    list.forEach(item => {
        const key = `${item.word}|||${item.hint}`;
        if (!masterMap.has(key)) {
            masterMap.set(key, { ...item, tags: [tag] });
        } else {
            const existing = masterMap.get(key);
            if (!existing.tags.includes(tag)) {
                existing.tags.push(tag);
            }
        }
    });
}

addToMap(classic, 'classic');
addToMap(mamak, 'mamak');
addToMap(hard, 'hard_words');
addToMap(fever, 'word_fever');

const values = [];
masterMap.forEach((data) => {
    const escapedWord = data.word.replace(/'/g, "''");
    const escapedHint = data.hint.replace(/'/g, "''");
    const escapedCategory = data.category.replace(/'/g, "''");
    const tagsSql = `ARRAY[${data.tags.map(t => `'${t}'`).join(',')}]`;
    values.push(`('${escapedWord}', '${escapedHint}', '${escapedCategory}', ${tagsSql})`);
});

let sql = `-- PEYVÇÎN VOCABULARY SYNC
-- Ensure a clean state by dropping the existing table if it exists
DROP TABLE IF EXISTS public.words CASCADE;

-- Table Structure
CREATE TABLE public.words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  word TEXT NOT NULL,
  hint TEXT,
  category TEXT,
  mode_tags TEXT[],
  UNIQUE(word, hint)
);

-- Batch Insert
INSERT INTO public.words (word, hint, category, mode_tags) VALUES
` + values.join(',\n') + ';\n';
sql += "\n-- Update notes: This ensures all game modes have access to the latest library.";

fs.writeFileSync('d:/Peyivcin App/supabase_vocabulary_sync.sql', sql);
console.log(`Successfully generated SQL with ${masterMap.size} unique word entries.`);
