const fs = require('fs');
const path = require('path');

const content = fs.readFileSync(path.join(__dirname, '../src/data/wordList.js'), 'utf8');

function getRange(arrayName) {
    const startRegex = new RegExp(`const ${arrayName} = \\[`);
    const startMatch = content.match(startRegex);
    if (!startMatch) return null;
    
    const startIndex = startMatch.index;
    let depth = 0;
    for (let i = startIndex + startMatch[0].length - 1; i < content.length; i++) {
        if (content[i] === '[') depth++;
        if (content[i] === ']') {
            depth--;
            if (depth === 0) {
                return { start: startIndex, end: i + 1 };
            }
        }
    }
    return null;
}

const ranges = {
    classic: getRange('classicWords'),
    hard_words: getRange('hardWords'),
    mamak: getRange('mamakWords'),
    word_fever: getRange('wordFeverWords'),
    names: getRange('humanNamesRaw')
};

const wordsMap = new Map();

// Find all objects
const objectRegex = /\{[\s\S]*?\}/g;
let objMatch;
while ((objMatch = objectRegex.exec(content)) !== null) {
    const objText = objMatch[0];
    const pos = objMatch.index;
    
    const wordM = objText.match(/word:\s*["']([^"']+)["']/);
    const hintM = objText.match(/hint:\s*["']([^"']+)["']/);
    const catM = objText.match(/category:\s*["']([^"']+)["']/);
    
    if (wordM && hintM) {
        const word = wordM[1];
        const hint = hintM[1];
        const category = catM ? catM[1] : 'گشتی';
        const key = `${word}|${hint}`;
        
        if (!wordsMap.has(key)) {
            wordsMap.set(key, { word, hint, category, modes: new Set() });
        }
        
        const data = wordsMap.get(key);
        
        for (const [mode, range] of Object.entries(ranges)) {
            if (range && pos >= range.start && pos <= range.end) {
                if (mode === 'names') {
                    if (word.length >= 2 && word.length <= 5) data.modes.add('classic');
                    if (word.length >= 6) data.modes.add('hard_words');
                } else {
                    data.modes.add(mode);
                }
            }
        }
    }
}

let sql = `-- PEYVÇÎN VOCABULARY SYNC - GENERATED ON ${new Date().toISOString()}\n`;
sql += `DROP TABLE IF EXISTS public.words CASCADE;\n\n`;
sql += `CREATE TABLE public.words (\n`;
sql += `  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n`;
sql += `  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),\n`;
sql += `  word TEXT NOT NULL,\n`;
sql += `  hint TEXT,\n`;
sql += `  category TEXT,\n`;
sql += `  mode_tags TEXT[],\n`;
sql += `  UNIQUE(word, hint)\n`;
sql += `);\n\n`;

sql += `-- Enable Row Level Security\n`;
sql += `ALTER TABLE public.words ENABLE ROW LEVEL SECURITY;\n\n`;

sql += `-- Create policy to allow anyone to read words\n`;
sql += `CREATE POLICY "Allow public read access" ON public.words\n`;
sql += `  FOR SELECT USING (true);\n\n`;

sql += `INSERT INTO public.words (word, hint, category, mode_tags) VALUES\n`;

const values = Array.from(wordsMap.values()).map(w => {
    const word = w.word.replace(/'/g, "''");
    const hint = w.hint.replace(/'/g, "''");
    const category = w.category.replace(/'/g, "''");
    const modes = Array.from(w.modes).map(m => `'${m}'`);
    if (modes.length === 0) modes.push("'classic'");
    return `('${word}', '${hint}', '${category}', ARRAY[${modes.join(',')}])`;
});

sql += values.join(',\n') + ';\n';

fs.writeFileSync(path.join(__dirname, '../supabase_vocabulary_sync.sql'), sql);
console.log(`Generated SQL with ${values.length} words.`);
